"""Typeset one algorithm entry as a Typst document, and optionally a PDF.

The HTML site is for browsing. This is for the other things a registry entry
gets used as: something to print, attach to a review, cite, or hand to a
colleague who will never install anything. Typst renders our stored LaTeX
through the `mitex` package, so the maths a paper needs and the maths the site
shows come from the same field.

Two modes. The default is a clean, citable sheet. `review=True` widens the
right margin and puts the open questions from `gigi review` there as margin
notes -- the PDF becomes the review artifact, with the gaps pointing at the
sections they concern.

Compilation needs the `typst` Python package (`pip install gigi-algo[docs]`).
Rendering the `.typ` source does not.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

from gigi import __version__, people, registry
from gigi.harness import verify
from gigi.models import MethodSpec, VerificationReport

PACKAGES = {
    "mitex": "@preview/mitex:0.2.6",  # renders the LaTeX we store
    "hydra": "@preview/hydra:0.6.3",  # running section headers
    "dashy-todo": "@preview/dashy-todo:0.1.3",  # margin notes in review mode
}

# The same palette as the site, so a printed entry and a browsed one read as
# one system. Names avoid Typst built-ins (`line`, `table`, `text`).
_PALETTE = """#let accent = rgb("#3b5bdb")
#let ok = rgb("#147a4b")
#let bad = rgb("#b42318")
#let warn = rgb("#8a5b00")
#let ink = rgb("#14171f")
#let muted = rgb("#5a6172")
#let rule = rgb("#e2e5ee")
#let panel = rgb("#f6f7fa")
#let sans = ("IBM Plex Sans", "Libertinus Serif")
#let mono = ("IBM Plex Mono", "DejaVu Sans Mono")
"""

_COMPONENTS = """#let pill(body, color: muted) = box(
  inset: (x: 5pt, y: 1.5pt), radius: 9pt, stroke: 0.5pt + color, baseline: 20%,
  text(size: 7.5pt, fill: color, font: mono, body))

#let card(body, color: muted) = block(
  width: 100%, inset: (x: 11pt, y: 9pt), radius: 4pt, fill: panel, above: 6pt, below: 8pt,
  stroke: (left: 2.5pt + color, rest: 0.4pt + rule), body)

#let tbl(..args) = table(
  ..args,
  stroke: (x, y) => if y == 0 { (bottom: 0.6pt + rule) } else { (bottom: 0.4pt + rule) },
  fill: (x, y) => if y == 0 { panel },
  inset: 6pt,
)
#show table.cell.where(y: 0): set text(size: 7.5pt, weight: 500, fill: muted, tracking: 0.06em)
#show table.cell.where(y: 0): upper
"""

_ESCAPE = str.maketrans({c: f"\\{c}" for c in "#*_@<>$\\[]`"})


def esc(text: object) -> str:
    """Make prose safe inside Typst markup."""
    return str(text).strip().translate(_ESCAPE)


def _raw(text: object) -> str:
    """An identifier in a raw span, where Typst escapes nothing."""
    return f"`{str(text).strip()}`"


def _pill(text: str, color: str = "muted") -> str:
    return f"#pill(color: {color})[{text}]"


def _math(latex: str | None, fallback: str, block: bool = True) -> str:
    if latex:
        return f"#{'mitex' if block else 'mi'}(`{latex.strip()}`)"
    return f"```\n{fallback.strip()}\n```"


def _table(columns: str, headers: list[str], rows: list[list[str]]) -> str:
    cells = ", ".join(f"[{esc(h)}]" for h in headers)
    body = ",\n  ".join(", ".join(f"[{c}]" for c in row) for row in rows)
    return f"#tbl(columns: {columns},\n  {cells},\n  {body}\n)\n"


def _names(ids: list[str]) -> str:
    return ", ".join(esc(people.get_person(i).name) if people.exists(i) else esc(i) for i in ids)


def _muted(text: str, size: float = 9) -> str:
    return f"#text(size: {size}pt, fill: muted)[{text}]"


def _todo(text: str, color: str = "warn") -> str:
    """A margin note. Only emitted in review mode; callers guard on that."""
    return f"#todo(position: right, stroke: {color})[{esc(text)}]"


# --- document frame -------------------------------------------------------------


def _preamble(spec: MethodSpec, review: bool) -> str:
    right = "4.4cm" if review else "2cm"
    imports = "\n".join(
        [
            f'#import "{PACKAGES["mitex"]}": mitex, mi',
            f'#import "{PACKAGES["hydra"]}": hydra',
            f'#import "{PACKAGES["dashy-todo"]}": todo' if review else "",
        ]
    )
    footer = (
        f"Generated by gigi {esc(__version__)} on {date.today().isoformat()}. "
        "Every number here came from running the algorithm."
    )
    return f"""{imports}
{_PALETTE}
#set page(
  margin: (top: 2.4cm, bottom: 2.2cm, left: 2cm, right: {right}),
  header: context {{
    set text(size: 8pt, fill: muted)
    grid(columns: (1fr, auto), [Gigi · {esc(spec.name)}], emph(hydra(2)))
    line(length: 100%, stroke: 0.4pt + rule)
  }},
  footer: context {{
    set text(size: 8pt, fill: muted)
    grid(columns: (1fr, auto), [{footer}], counter(page).display("1"))
  }},
)
#set text(font: sans, size: 10pt, fill: ink)
#set par(justify: false, leading: 0.62em)
#show raw: set text(font: mono, size: 8.5pt)
#set heading(numbering: none)
#show heading.where(level: 1): set text(size: 22pt, weight: 600)
#show heading.where(level: 2): it => {{ v(10pt); text(size: 13pt, weight: 600, it.body); v(3pt) }}
#show heading.where(level: 3): it => {{
  v(5pt); text(size: 8.5pt, weight: 500, fill: muted, tracking: 0.08em, upper(it.body)); v(1pt) }}
{_COMPONENTS}
"""


# --- sections ---------------------------------------------------------------------


def _header(spec: MethodSpec) -> list[str]:
    return [
        f"= {esc(spec.name)}",
        " ".join(
            [
                _pill(esc(spec.family)),
                _pill(esc(spec.maturity.value), "accent" if spec.maturity.value == "stable" else "muted"),
                _pill(f"output: {esc(spec.output.kind.value)}"),
            ]
        ),
        "#v(4pt)",
        esc(spec.summary),
        "",
    ]


def _maths(spec: MethodSpec, review: bool) -> list[str]:
    maths = spec.maths
    if not (maths.summary or maths.definition):
        return []
    out = ["== Mathematics", esc(maths.summary), ""]
    for formula in filter(None, [maths.definition, *maths.also]):
        out.append(f"#card(color: accent)[\n  {_math(formula.latex, formula.statement)}\n]")
        if formula.note:
            out += [_muted(esc(formula.note)), ""]

    if maths.invariants:
        out.append("=== Invariants")
        out.append(_table(
            "(auto, 1fr, auto)",
            ["invariant", "statement", "checked"],
            [[_raw(i.id),
              _math(i.latex, i.statement, block=False) if i.latex else esc(i.statement),
              _pill("every run", "ok") if i.check else _pill("documented")]
             for i in maths.invariants],
        ))

    if maths.under_determined:
        rows = []
        for c in maths.under_determined:
            if c.divergences:
                measured = _pill("backends differ", "bad") + " " + ", ".join(_raw(d) for d in c.divergences)
            elif c.datasets:
                measured = _pill("backends agree", "ok") + " on " + ", ".join(_raw(d) for d in c.datasets)
            else:
                measured = _pill("untested", "warn")
                if review:
                    measured += _todo(f"No fixture tests the '{c.id}' choice point yet.")
            rows.append([esc(c.question), " \\\n".join(f"– {esc(ch)}" for ch in c.choices), measured])
        out.append("=== Where the definition leaves a choice")
        out.append(_table("(1fr, 1.2fr, 1fr)", ["question", "defensible answers", "measured"], rows))
    return out


def _origin(spec: MethodSpec) -> list[str]:
    prov = spec.provenance
    if not (prov.original_authors or prov.original_work):
        return []
    out = ["== Origin"]
    if prov.original_authors:
        year = f" ({prov.introduced})" if prov.introduced else ""
        out += [f"*Original authors{year}.* " + ", ".join(esc(a.name) for a in prov.original_authors), ""]
    if prov.original_work:
        w = prov.original_work
        detail = ", ".join(esc(x) for x in (w.venue, w.year, w.doi) if x is not None)
        out += [f"*Original work.* _{esc(w.title)}_ — {detail}", ""]
    if prov.precursors:
        out.append(_table(
            "(1fr, auto, 1.4fr)",
            ["precursor", "authors", "relationship"],
            [[esc(p.name) + (f" ({p.year})" if p.year else ""),
              ", ".join(esc(a) for a in p.authors), esc(p.note or "")] for p in prov.precursors],
        ))
    if prov.attribution_notes:
        out += [_muted(esc(prov.attribution_notes)), ""]
    return out


def _parameters_and_engines(spec: MethodSpec, review: bool) -> list[str]:
    missing = sorted(
        set(registry.plausible_backends(spec)) - set(registry.implemented_backends(spec.id))
    )
    engines_heading = "== Backends"
    if review and missing:
        engines_heading += _todo(f"No implementation yet for: {', '.join(missing)}.", "accent")
    return [
        "== Parameters",
        _table(
            "(auto, auto, auto, 1fr)",
            ["parameter", "type", "Gigi default", "meaning"],
            [[_raw(p.name), esc(p.type),
              "_engine default_" if p.common_default is None else _raw(p.common_default),
              esc(p.description)] for p in spec.parameters],
        ),
        engines_heading,
        _table("(auto, 1fr)", ["backend", "notes"],
               [[_raw(n), esc(s.notes or "")] for n, s in spec.backends.items()]),
    ]


_SEVERITY_COLOR = {"critical": "bad", "high": "bad", "medium": "warn", "low": "muted", "info": "muted"}


def _divergences(spec: MethodSpec, report: VerificationReport | None, review: bool) -> list[str]:
    if not spec.divergences:
        return []
    checks = {c.divergence_id: c for c in (report.divergence_checks if report else [])}
    out = ["== Divergences"]
    for d in spec.divergences:
        color = _SEVERITY_COLOR.get(d.severity.value, "muted")
        check = checks.get(d.id)
        if check is None:
            evidence = _pill("not checked")
        elif check.observed == "skipped":
            evidence = _pill("skipped", "warn") + " " + esc(check.note)
            if review:
                evidence += _todo(f"'{d.id}' could not be checked here: {check.note}")
        elif check.reproduced:
            evidence = _pill("reproduced", "ok") + " on " + ", ".join(_raw(x) for x in check.datasets)
        else:
            evidence = _pill("did not reproduce", "bad") + " " + esc(check.note)
        found = f" Found by {_names(d.discovered_by)}." if d.discovered_by else ""
        tags = " ".join([_pill(esc(d.category.value)), _pill(f"severity {esc(d.severity.value)}", color),
                         *(_pill(esc(e)) for e in d.backends)])
        body = [
            f"{_raw(d.id)} #h(6pt) {tags}",
            "",
            esc(d.summary),
            "",
            f"*Consequence.* {esc(d.consequence)}" if d.consequence else "",
            "",
            f"*Evidence.* {evidence}.{found}",
        ]
        out.append(f"#card(color: {color})[\n" + "\n".join(f"  {b}" for b in body) + "\n]")
    return out


def _verification(report: VerificationReport | None, review_result) -> list[str]:
    if report is None:
        return []
    backends = ", ".join(f"{_raw(e)} {esc(report.backend_versions.get(e) or '')}" for e in report.backends)
    status = _pill(esc(report.status.upper()), "ok" if report.status == "pass" else "bad")
    out = [
        "== Verification",
        f"{status} {esc(report.conclusion)}",
        "",
        f"Backends: {backends}. {len(report.runs)} runs, "
        f"{sum(len(r.invariants) for r in report.runs)} invariant assertions, "
        f"{len(report.explained_differences)} difference(s) explained by declared divergences.",
        "",
    ]
    if review_result is not None:
        target, lacking = review_result.promotion
        if target and not lacking:
            out.append(_todo(f"Meets every requirement of {target}. Ready to promote.", "accent"))
        for item in lacking:
            out.append(_todo(f"For {target}: {item}"))
        for gap in review_result.gaps:
            if "implementation yet" in gap or "choice point" in gap or "not checked here" in gap:
                continue  # already placed beside the section it concerns
            out.append(_todo(gap))
    return out


def _credits(spec: MethodSpec) -> list[str]:
    credits = spec.credits
    if not credits.everyone():
        return []
    pairs = [("steward", credits.stewards), ("specification", credits.spec_curators),
             ("reference implementation", credits.reference_implementation),
             ("verifier", credits.verifier_authors), ("dataset curation", credits.dataset_curators),
             ("review", credits.reviewers)]
    pairs += [(f"{e} adapter", ids) for e, ids in sorted(credits.adapter_contributors.items())]
    return ["== Gigi contributors",
            _table("(auto, 1fr)", ["role", "people"], [[esc(l), _names(ids)] for l, ids in pairs if ids])]


def _for_the_reviewer(review_result) -> list[str]:
    if review_result is None:
        return []
    out = ["== For the reviewer", _muted("Nothing automated settles these. Tick each, or say why not."), ""]
    for index, item in enumerate(review_result.by_eye, 1):
        out += [
            f"#box(width: 1em)[#sym.ballot] *{index}. {esc(item.question)}*",
            f"#block(inset: (left: 1.4em), above: 2pt, below: 8pt)[",
            f"  {_muted('look at: ' + esc(item.where), 8.5)} \\",
            f"  {_muted(esc(item.why), 8.5)}",
            "]",
            "",
        ]
    return out


# --- public -----------------------------------------------------------------------


def render(spec: MethodSpec, report: VerificationReport | None = None, review_result=None) -> str:
    """The full entry as Typst source. Pass a `Review` to get margin notes."""
    review = review_result is not None
    lines = [_preamble(spec, review)]
    for section in (
        _header(spec),
        _maths(spec, review),
        _origin(spec),
        _parameters_and_engines(spec, review),
        _divergences(spec, report, review),
        _verification(report, review_result),
        _credits(spec),
        _for_the_reviewer(review_result),
    ):
        lines.extend(section)
    return "\n".join(lines) + "\n"


def compile_available() -> bool:
    """Is the optional typst compiler installed?"""
    try:
        import typst  # noqa: F401
    except ImportError:
        return False
    return True


def write(
    method_id: str,
    output_dir: str | Path = "site/typst",
    pdf: bool = False,
    verify_first: bool = True,
    review: bool = False,
) -> list[Path]:
    """Write `<id>.typ`, and `<id>.pdf` when asked and the compiler is installed.

    `review=True` adds the open questions from `gigi review` as margin notes and
    a reviewer's checklist; the file is then named `<id>.review.typ`.
    """
    spec = registry.load_method(method_id)
    report = verify(spec) if verify_first or review else None
    review_result = None
    if review:
        from gigi.review import review as run_review

        review_result = run_review(method_id)

    directory = Path(output_dir)
    directory.mkdir(parents=True, exist_ok=True)
    stem = f"{method_id}.review" if review else method_id

    source = directory / f"{stem}.typ"
    source.write_text(render(spec, report, review_result), encoding="utf-8")
    written = [source]

    if pdf:
        if not compile_available():
            raise RuntimeError("PDF output needs the typst package: pip install 'gigi-algo[docs]'")
        import typst

        target = directory / f"{stem}.pdf"
        target.write_bytes(typst.compile(str(source)))
        written.append(target)
    return written
